[package]
name = "solana-core"
description = "Blockchain, Rebuilt for Scale"
version = "1.5.14"
documentation = "https://docs.rs/solana"
homepage = "https://solana.com/"
readme = "../README.md"
repository = "https://github.com/solana-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2018"

[badges]
codecov = { repository = "solana-labs/solana", branch = "master", service = "github" }

[dependencies]
ahash = "0.6.1"
base64 = "0.12.3"
bincode = "1.3.1"
bv = { version = "0.11.1", features = ["serde"] }
bs58 = "0.3.1"
byteorder = "1.3.4"
chrono = { version = "0.4.11", features = ["serde"] }
core_affinity = "0.5.10"
crossbeam-channel = "0.4"
ed25519-dalek = "=1.0.0-pre.4"
fs_extra = "1.2.0"
flate2 = "1.0"
indexmap = { version = "1.5", features = ["rayon"] }
itertools = "0.9.0"
jsonrpc-core = "15.0.0"
jsonrpc-core-client = { version = "15.0.0", features = ["ws"] }
jsonrpc-derive = "15.0.0"
jsonrpc-http-server = "15.0.0"
jsonrpc-pubsub = "15.0.0"
jsonrpc-ws-server = "15.0.0"
log = "0.4.11"
lru = "0.6.1"
miow = "0.2.2"
net2 = "0.2.37"
num-traits = "0.2"
rand = "0.7.0"
rand_chacha = "0.2.2"
raptorq = "1.4.2"
rayon = "1.4.1"
regex = "1.3.9"
retain_mut = "0.1.2"
rustversion = "1.0.4"
serde = "1.0.118"
serde_bytes = "0.11"
serde_derive = "1.0.103"
serde_json = "1.0.56"
solana-account-decoder = { path = "../account-decoder", version = "1.5.14" }
solana-banks-server = { path = "../banks-server", version = "1.5.14" }
solana-clap-utils = { path = "../clap-utils", version = "1.5.14" }
solana-client = { path = "../client", version = "1.5.14" }
solana-faucet = { path = "../faucet", version = "1.5.14" }
solana-ledger = { path = "../ledger", version = "1.5.14" }
solana-logger = { path = "../logger", version = "1.5.14" }
solana-merkle-tree = { path = "../merkle-tree", version = "1.5.14" }
solana-metrics = { path = "../metrics", version = "1.5.14" }
solana-measure = { path = "../measure", version = "1.5.14" }
solana-net-utils = { path = "../net-utils", version = "1.5.14" }
solana-perf = { path = "../perf", version = "1.5.14" }
solana-program-test = { path = "../program-test", version = "1.5.14" }
solana-runtime = { path = "../runtime", version = "1.5.14" }
solana-sdk = { path = "../sdk", version = "1.5.14" }
solana-frozen-abi = { path = "../frozen-abi", version = "1.5.14" }
solana-frozen-abi-macro = { path = "../frozen-abi/macro", version = "1.5.14" }
solana-stake-program = { path = "../programs/stake", version = "1.5.14" }
solana-storage-bigtable = { path = "../storage-bigtable", version = "1.5.14" }
solana-streamer = { path = "../streamer", version = "1.5.14" }
solana-sys-tuner = { path = "../sys-tuner", version = "1.5.14" }
solana-transaction-status = { path = "../transaction-status", version = "1.5.14" }
solana-version = { path = "../version", version = "0.2.0" }
solana-vote-program = { path = "../programs/vote", version = "1.5.14" }
spl-token-v2-0 = { package = "spl-token", version = "=3.1.0", features = ["no-entrypoint"] }
hex = "0.4.2"
rlp = "0.5"
sha3 = "0.9.1"
primitive-types = "0.8.0"
secp256k1 = { version = "0.19.0", features = ["recovery", "global-context"] }
evm-state = { path = "../evm-utils/evm-state" }
evm-rpc = { path = "../evm-utils/evm-rpc" }
solana-evm-loader-program = { path = "../evm-utils/programs/evm_loader" }
tempfile = "3.1.0"
thiserror = "1.0"
tokio = { version = "0.2", features = ["full"] }
tokio_01 = { version = "0.1", package = "tokio" }
tokio_01_bytes = { version = "0.4.7", package = "bytes" }
tokio_fs_01 = { version = "0.1", package = "tokio-fs" }
tokio_io_01 = { version = "0.1", package = "tokio-io" }
tokio_codec_01 = { version = "0.1", package = "tokio-codec" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "1.5.14" }
trees = "0.2.1"
snafu = "0.6"
anyhow = "1"

[dev-dependencies]
matches = "0.1.6"
num_cpus = "1.13.0"
reqwest = { version = "0.10.8", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serial_test = "0.4.0"
serial_test_derive = "0.4.0"
systemstat = "0.1.5"

[build-dependencies]
rustc_version = "0.2"

[[bench]]
name = "banking_stage"

[[bench]]
name = "blockstore"

[[bench]]
name = "crds"

[[bench]]
name = "crds_gossip_pull"

[[bench]]
name = "crds_shards"

[[bench]]
name = "gen_keys"

[[bench]]
name = "sigverify_stage"

[[bench]]
name = "poh"

[[bench]]
name = "retransmit_stage"

[[bench]]
name = "cluster_info"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[features]
default = []
multiple-db-in-thread = []
